Make image a regular writable root image.

diff --git a/files/etc/init.d/hostname-init b/files/etc/init.d/hostname-init
--- a/files/etc/init.d/hostname-init
+++ b/files/etc/init.d/hostname-init
@@ -20,14 +20,14 @@ case "$1" in
         mac=`cat /sys/class/net/eth0/address | sed s/://g`
         hostname="odroidc1-$mac"
         log_action_begin_msg "Creating /etc/hostname with $hostname"
-        mount -n -o remount,rw / || echo "Remounting / rw failed"
+#       mount -n -o remount,rw / || echo "Remounting / rw failed"
         echo "$hostname" > /etc/hostname
         hostname "$hostname"
         if ! grep "^127.0.0.1\s*$hostname\s*" /etc/hosts > /dev/null ; then
             sed -i "1i 127.0.0.1\\t$hostname" /etc/hosts
         fi
-        sync || echo "sync failed"
-        mount -n -o remount,ro / || echo "Remounting / ro failed"
+#       sync || echo "sync failed"
+#       mount -n -o remount,ro / || echo "Remounting / ro failed"
         log_action_end_msg 0
     fi
     ;;
diff --git a/patches/ssh.patch b/patches/ssh.patch
--- a/patches/ssh.patch
+++ b/patches/ssh.patch
@@ -8,12 +8,12 @@
 +    if run_by_init; then
 +        if [ ! -e /etc/ssh/ssh_host_rsa_key ]; then
 +            log_action_msg "Generating SSH host keys..." || true
-+            mount -n -o remount,rw / || echo "Remounting / rw failed"
++#           mount -n -o remount,rw / || echo "Remounting / rw failed"
 +            ssh-keygen -q -t rsa -N "" -f /etc/ssh/ssh_host_rsa_key
 +            ssh-keygen -q -t dsa -N "" -f /etc/ssh/ssh_host_dsa_key
 +            ssh-keygen -q -t ecdsa -N "" -f /etc/ssh/ssh_host_ecdsa_key
-+            sync || echo "sync failed"
-+            mount -n -o remount,ro / || echo "Remounting / ro failed"
++#           sync || echo "sync failed"
++#           mount -n -o remount,ro / || echo "Remounting / ro failed"
 +        fi
 +    fi
 +}
