Add support for ODROID-C2 and ability to create ro/rw images based on ROOT_RW make flag.

diff --git a/files/common/etc/init.d/hostname-init b/files/common/etc/init.d/hostname-init
--- a/files/common/etc/init.d/hostname-init
+++ b/files/common/etc/init.d/hostname-init
@@ -1,33 +1,50 @@
-#!/bin/sh -e
+#!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          hostname-init
 # Required-Start:    
 # Required-Stop:     
 # Default-Start:     S
 # Default-Stop:      
-# X-Start-Before:    hostname
+# X-Start-After:     networking
 # Short-Description: Creates /etc/hostname if missing.
 # Description:       Creates the /etc/hostname file on the first boot.
 ### END INIT INFO
 
 PATH="/sbin:/bin"
 
+. /lib/init/vars.sh
 . /lib/lsb/init-functions
 
 case "$1" in
     start)
     if [ ! -e "/etc/hostname" ]; then
         mac=`cat /sys/class/net/eth0/address | sed s/://g`
-        hostname="odroidc1-$mac"
-        log_action_begin_msg "Creating /etc/hostname with $hostname"
-#       mount -n -o remount,rw / || echo "Remounting / rw failed"
-        echo "$hostname" > /etc/hostname
-        hostname "$hostname"
-        if ! grep "^127.0.0.1\s*$hostname\s*" /etc/hosts > /dev/null ; then
-            sed -i "1i 127.0.0.1\\t$hostname" /etc/hosts
+        if [ "$mac" = "000000000000" ]; then
+            log_action_begin_msg "No MAC address, not creating /etc/hostname!"
+        else
+            LOCKDIR="/var/lock/remount_rootfs"
+            until mkdir "$LOCKDIR" 2>/dev/null; do
+                sleep 1
+            done
+            
+            RO_ROOT=`grep -c -E "\s/\s[[:alnum:]]+\sro[\s,]" /proc/mounts`
+            hostname="odroidc-$mac"
+            log_action_begin_msg "Creating /etc/hostname with $hostname"
+            if [ "$RO_ROOT" != "0" ]; then
+                mount -n -o remount,rw / || echo "Remounting / rw failed"
+            fi
+            echo "$hostname" > /etc/hostname
+            hostname "$hostname"
+            if ! grep "^127.0.0.1\s*$hostname\s*" /etc/hosts > /dev/null ; then
+                sed -i "1i 127.0.0.1\\t$hostname" /etc/hosts
+            fi
+            if [ "$RO_ROOT" != "0" ]; then
+                sync || echo "sync failed"
+                mount -n -o remount,ro / || echo "Remounting / ro failed"
+            fi
+            
+            rm -rf "$LOCKDIR"
         fi
-#       sync || echo "sync failed"
-#       mount -n -o remount,ro / || echo "Remounting / ro failed"
         log_action_end_msg 0
     fi
     ;;
